'use strict';

require('dotenv').config();

const express = require('express');
const googleTranslate = require('google-translate')(process.env.TRANSLATE_KEY);
const app = express();
const watson = require('watson-developer-cloud');

var text_to_speech = watson.text_to_speech({  //The un and pw generated by IBM watson are saved in the
  username: process.env.WATSON_UN,			  //.env file this is used to access Watson's text-to-speech
  password: process.env.WATSON_PW,            //API without needing to enter credentials each time.
  version: 'v1'
});
 

app.use('/', express.static(`${__dirname}/public`));

app.get('/translate', (req, res) => {
	let text = req.query.text;

	res.set('content-type', 'application/json')
	googleTranslate.translate(text, 'it', function(err, translation) {
		if (err) {
			res.status(500).send({ error: err.message })
		}
		else{
			res.send({ translation: translation.translatedText });
		}
	});
});

app.get('/text-to-speech.ogg', (req, res) => {
	res.set('content-type', 'audio/ogg');


	var params = {
	  text: req.query.text,
	  voice: 'it-IT_FrancescaVoice', // Optional voice for Italian.
	  accept: 'audio/ogg'
	};
	 
	// Piping the synthesized text to a file 
	text_to_speech.synthesize(params).pipe(res);

});

let port = parseFloat(process.env.PORT) || 3000;

console.log(`Listening on port ${port}`)

app.listen(
	port
);